### ISSUE TITLE
Typo(s) in live message?

### ISSUE THREAD

**Issue by CrystalENVT** [dopeghoti/DiscordCurrentlyCastingBot#16]
I think the below message is supposed to be "their" presence & "their" mic, not "eir"

`
What if I told you that <User> has blessed us with eir presence!  Check em out at https://twitch.tv/<user> and let em know if eir mic has been muted this whole time.
`

Fabulous or "frabjous", also "their" vs "eir"

`O frabjous day! <user> is presenting to the masses!  Enjoy eir show at https://twitch.tv/<user> and report back when they are finished`

**Comment by dopeghoti** [comment]
'Frabjous' is lifted from Lewis Caroll's _Jabberwocky_:

> “And hast thou slain the Jabberwock?
>       Come to my arms, my beamish boy!
> O frabjous day! Callooh! Callay!”
>       He chortled in his joy.
> 

'Ey', 'eir', and 'em' are Spivak pronouns: non-gender-specific singular pronouns that can be used in lieu of the non-gender-specific plural "they", "their", and "them".  Other Spivak forms include 'ze/zey/zem' and 'xe/xey/xem'.

That said, the phrase fragments that are used are in `bot.py` on lines 273-310 in the `main` branch as of this writing; they can be added to or changed freely followed by a bot restart to make the changes active.

I am planning on adding the ability to make these configurable without editing the code, possibly via the Discord "control" channel.

**Comment by CrystalENVT** [comment]
Thanks for the clarification, just wanted to check on this.

Alternative to a control channel, maybe just a json or yaml file with a list of substrings to use would be fine. Just load those substrings in to where they are used in the program currently
